import express from "express";
import { protectRoute } from "../middleware/protectRoute.js";
import { createPost } from "../controllers/postcontroller.js";
import {deletePost} from "../controllers/postcontroller.js";
import { commentOnPost } from "../controllers/postcontroller.js";
import {likeUnlikePost} from "../controllers/postcontroller.js";
import { getAllPosts } from "../controllers/postcontroller.js";
import { getLikedPosts } from "../controllers/postcontroller.js";
import { getFollowingPosts } from "../controllers/postcontroller.js";
import { getUserPosts } from "../controllers/postcontroller.js";
const router = express.Router();
router.get("/all",protectRoute,getAllPosts);
router.get("/likes/:id",protectRoute,getLikedPosts);
router.get("/following",protectRoute,getFollowingPosts);
router.get("/user/:username",protectRoute,getUserPosts);
router.post("/create",protectRoute,createPost);
router.post("/like/:id", protectRoute,likeUnlikePost);
router.post("/comment/:id",protectRoute,commentOnPost);
router.delete("/:id",protectRoute,deletePost);
export default router;